---
    name: "sample pipeline/workflows"
    on:
      push:
        branches: 
            - main 
            - master
      workflow_dispatch:
      pull_request:
        branches:
            - master

    jobs:
      sampleJob:
        runs-on: ubuntu-latest
        steps:
          - name: Print Hello World
            run: echo "hello world"
          - name: print current directory
            run: pwd
    